"""add embeddings to document chunks

Revision ID: 0233b64c6487
Revises: 25ba59da2b52
Create Date: 2026-07-23 18:01:20.725375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '0233b64c6487'
down_revision: Union[str, Sequence[str], None] = '25ba59da2b52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
    "document_chunks",
    sa.Column(
        "embedding",
        Vector(384),
        nullable=True,
    ),
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_chunks', 'embedding')
    # ### end Alembic commands ###
